// Run after npm run generate. Serves the SSG output under the production base URL.
import assert from 'node:assert/strict'
import { createServer } from 'node:http'
import { readFile, stat, mkdtemp } from 'node:fs/promises'
import { resolve, extname, sep } from 'node:path'
import { tmpdir } from 'node:os'
import { chromium } from 'playwright'

const root = resolve('docs')
const base = '/Yota_Website_Nuxt/'
const screenshots = await mkdtemp(resolve(tmpdir(), 'yota-live-'))
const mime = { '.html': 'text/html', '.js': 'text/javascript', '.css': 'text/css', '.json': 'application/json', '.png': 'image/png', '.woff2': 'font/woff2', '.avif': 'image/avif' }
const server = createServer(async (req, res) => {
  try {
    const pathname = decodeURIComponent(new URL(req.url, 'http://localhost').pathname)
    if (!pathname.startsWith(base)) { res.writeHead(404); res.end(); return }
    let file = resolve(root, pathname.slice(base.length))
    if (file !== root && !file.startsWith(root + sep)) { res.writeHead(403); res.end(); return }
    if ((await stat(file)).isDirectory()) file = resolve(file, 'index.html')
    res.setHeader('Content-Type', mime[extname(file)] || 'application/octet-stream')
    res.end(await readFile(file))
  } catch { res.writeHead(404); res.end() }
})
await new Promise((resolve, reject) => { server.once('error', reject); server.listen(0, '127.0.0.1', resolve) })
const url = `http://127.0.0.1:${server.address().port}${base}`
const browser = await chromium.launch({ headless: true })
try {
  const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } })
  const errors = []
  page.on('pageerror', error => errors.push(error.message))
  page.on('console', message => { if (/hydration/i.test(message.text())) errors.push(message.text()) })
  page.on('response', response => { if (response.status() >= 400 && /(_nuxt|live-host-demo)/.test(response.url())) errors.push(`${response.status()} ${response.url()}`) })
  const click = name => page.getByRole('button', { name, exact: true }).click()
  const visible = async text => assert.ok(await page.getByText(text, { exact: true }).isVisible(), text)
  const count = async (selector, expected) => assert.equal(await page.locator(selector).count(), expected, selector)
  async function noOverflow() {
    assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth + 1), 'no document horizontal overflow')
  }
  await page.goto(`${url}lobby/live/`)
  await visible('登入後進入直播')
  await click('立即登入 / 註冊')
  await page.locator('#login-account').fill('liveTester')
  await page.locator('#login-password').fill('prototype123')
  await click('登入')
  await page.locator('.live-card').first().waitFor()
  await page.locator('.login-overlay').waitFor({ state: 'hidden' }).catch(() => {})
  // The login completion animation closes after the session is initialized.
  await page.getByRole('button', { name: '關注 薇薇', exact: true }).click()
  await count('.live-card', 6)
  await noOverflow()
  await page.evaluate(() => window.scrollTo(0, 0))
  await page.screenshot({ path: `${screenshots}/desktop-lobby.png`, fullPage: true })
  const headerBefore = await page.locator('.lobby-header').innerText()
  await click('♥ 最愛')
  await count('.live-card', 1)
  await click('體育')
  await visible('找不到符合條件的直播')
  await click('♥ 最愛')
  await page.getByRole('searchbox', { name: '搜尋直播' }).fill('fifa')
  await count('.live-card', 1)
  await click('全部')
  await page.getByRole('searchbox', { name: '搜尋直播' }).fill('')
  await click('進入 薇薇 的直播間')
  assert.equal(await page.getByRole('button', { name: '♥ 已關注', exact: true }).getAttribute('aria-pressed'), 'true')
  await click('暫停示意')
  await visible('畫面示意已暫停')
  await click('播放示意')
  await click('取消靜音示意')
  assert.ok(await page.getByRole('button', { name: '靜音示意', exact: true }).isVisible())
  const input = page.getByRole('textbox', { name: '直播間訊息', exact: true })
  assert.equal(await input.getAttribute('maxlength'), '200')
  await input.fill('  ')
  assert.ok(await page.getByRole('button', { name: '發送示範訊息' }).isDisabled())
  await input.fill('你好，WEB直播！')
  await input.press('Enter')
  assert.ok((await page.getByRole('log').innerText()).includes('你好，WEB直播！'))
  await click('開啟示範贈禮')
  await click('送出')
  assert.ok((await page.getByRole('log').innerText()).includes('送出一顆示範愛心！'))
  assert.equal(await page.locator('.lobby-header').innerText(), headerBefore, 'free gift leaves wallet balances unchanged')
  await click('直播')
  await visible('薇薇 的直播間')
  await click('取消關注')
  await click('排行')
  await visible('本場支持榜')
  await click('聊天')
  await page.screenshot({ path: `${screenshots}/desktop-room.png`, fullPage: true })
  await click('返回直播大廳')
  assert.ok(await page.getByRole('button', { name: '關注 薇薇', exact: true }).isVisible())
  await click('進入 洛洛 的直播間')
  await visible('主播目前下播中')
  await click('開啟示範贈禮')
  await click('送出')
  await click('返回直播大廳')
  await click('我的')
  await count('.live-my .live-record-row', 1)
  await click('贈禮紀錄')
  await count('.live-my .live-record-row', 2)
  await click('直播預告')
  await visible('目前尚無直播預告')
  await click('直播排行')
  await click('送禮榜')
  await click('日榜')
  assert.equal(await page.locator('.live-place-1 em').innerText(), '500')
  assert.equal(await page.locator('.live-place-1 strong').innerText(), '星辰')
  await page.screenshot({ path: `${screenshots}/desktop-rank.png`, fullPage: true })

  for (const width of [768, 390, 320]) {
    await page.setViewportSize({ width, height: 844 })
    await click('直播大廳')
    await noOverflow()
    await page.screenshot({ path: `${screenshots}/${width}-lobby.png`, fullPage: true })
    await click('進入 薇薇 的直播間')
    await noOverflow()
    await page.evaluate(() => window.scrollTo(0, 0))
    await page.screenshot({ path: `${screenshots}/${width}-room.png`, fullPage: true })
    await page.getByRole('textbox', { name: '直播間訊息', exact: true }).fill(`手機 ${width} 測試`)
    await click('發送示範訊息')
    assert.ok((await page.getByRole('log').innerText()).includes(`手機 ${width} 測試`))
    await click('開啟示範贈禮')
    await click('送出')
    await click('直播排行')
    await noOverflow()
    await click('我的')
    await click('贈禮紀錄')
    await noOverflow()
  }
  await page.setViewportSize({ width: 1440, height: 1000 })
  // SPA navigation out of the live page must clear the session just like closing APP LiveCenter.
  await page.locator('.lobby-nav').getByRole('link', { name: '遊戲大廳', exact: true }).click()
  await page.waitForURL(`${url}lobby`)
  await page.locator('.lobby-nav').getByRole('link', { name: '直播', exact: true }).click()
  await click('我的')
  await visible('還沒有觀看紀錄')
  await click('贈禮紀錄')
  await visible('還沒有贈禮紀錄')
  await page.reload()
  await page.locator('.live-card').first().waitFor()
  await click('我的')
  await visible('還沒有觀看紀錄')
  assert.deepEqual(errors, [], 'no hydration, runtime or live asset failures')
  console.log('PASS: guest login, filters, favorites, room controls, chat, free gifts, histories, rankings, 1440/768/390/320 layouts, mobile interactions and session reset')
  console.log(`Screenshots: ${screenshots}`)
} finally {
  await browser.close()
  await new Promise(resolve => server.close(resolve))
}
